services:
  - type: web
    name: oracle-reconciliation-api
    env: python
    region: ohio
    plan: free
    buildCommand: "uv sync"
    startCommand: "uvicorn src.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ORACLE_USER
        sync: false
      - key: ORACLE_PASS
        sync: false
      - key: API_KEY
        sync: false

