from __future__ import annotations

# Networking Constants
DEFAULT_TIMEOUT = 15.0
MAX_CONNECTIONS = 200
DEFAULT_CONCURRENCY = 50

# BIP Constants
BIP_TIMEOUT = 60.0
BIP_CHUNK_DOWNLOAD_SIZE = -1
BIP_MAX_RETRIES = 3
BIP_MIN_WAIT_SECONDS = 1
BIP_MAX_WAIT_SECONDS = 10

# Oracle Matching Phases
PHASE_UNAPPLIED = 1
PHASE_APPLIED = 2
PHASE_OPEN = 1
PHASE_CLOSED_OR_OTHER = 2

# Oracle Status Codes & Types
STATUS_UNAPPLIED = "UNAPPLIED"
STATUS_APPLIED = "APPLIED"
STATUS_OPEN = "OPEN"
STATUS_CLOSED = "CLOSED"
STATUS_OTHER = "OTHER"


