from __future__ import annotations

import os

# Networking Constants
DEFAULT_TIMEOUT = 15.0
MAX_CONNECTIONS = 1000
DEFAULT_CONCURRENCY = 100

# BIP Constants
BIP_TIMEOUT = 180.0
BIP_CHUNK_DOWNLOAD_SIZE = -1
BIP_MAX_RETRIES = 3
BIP_MIN_WAIT_SECONDS = 1
BIP_MAX_WAIT_SECONDS = 10
_ttl_str = os.getenv("BIP_CACHE_TTL_SECONDS", "60").strip()
BIP_CACHE_TTL_SECONDS = int(_ttl_str) if _ttl_str else 60

# Oracle Matching Phases
PHASE_UNAPPLIED = 1
PHASE_APPLIED = 2
PHASE_OPEN = 1
PHASE_CLOSED_OR_OTHER = 2

# Oracle Status Codes & Types
STATUS_UNAPPLIED = "UNAPPLIED"
STATUS_APPLIED = "APPLIED"
STATUS_OPEN = "OPEN"
STATUS_CLOSED = "CLOSED"
STATUS_OTHER = "OTHER"
